apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-a3
  labels:
    app: my-app-a3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-a3
  template:
    metadata:
      labels:
        app: my-app-a3
    spec:
      containers:
      - name: waiter
        image: waiter:v1
        ports:
        - containerPort: 80